namespace ScreenRecorderApp.Models;

/// <summary>
/// A drawing tool on the live annotation overlay's floating toolbar. <see cref="Pen"/> is freehand;
/// the four shape tools rubber-band between a press and a release; <see cref="Text"/> drops a typed
/// label at the click point.
/// </summary>
public enum AnnotationTool
{
    Select,
    Pen,
    Highlighter,
    Marker,
    Line,
    Arrow,
    DoubleArrow,
    Rectangle,
    Square,
    Ellipse,
    Circle,
    RoundedRectangle,
    Triangle,
    Diamond,
    FlowchartProcess,
    FlowchartDecision,
    StartEnd,
    Database,
    Document,
    User,
    Server,
    Monitor,
    Mobile,
    Folder,
    Callout,
    Cloud,
    SpeechBubble,
    ThoughtBubble,
    Label,
    Tag,
    PointerCallout,
    CurvedLine,
    ElbowLine,
    DashedLine,
    Bezier,
    Measurement,
    Blur,
    Pixelate,
    Magnifier,
    SpotlightRectangle,
    Underline,
    StrikeThrough,
    Check,
    Cross,
    Warning,
    Info,
    Question,
    Cursor,
    Click,
    KeyboardBadge,
    CodeFrame,
    TerminalFrame,
    BrowserFrame,
    Braces,
    Crosshair,
    NumberedStep,
    Spotlight,
    Text,
}
